apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-test
  namespace: default-app
spec:
  action: pod-failure
  mode: one
  duration: '60s'
  selector:
    labelSelectors:
      'app': 'go-app'
  scheduler:
    cron: '@every 2m'
