# 3. The Go App (Deployment)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  namespace: default-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: jaiminops18/go-app:secure-v1 # (Or your latest tag)
        imagePullPolicy: Always
        env:
        - name: REDIS_HOST
          value: "redis-service:6379"
        ports:
        - containerPort: 8080
---
# 4. Go App Service (External Access)
apiVersion: v1
kind: Service
metadata:
  name: go-service
  namespace: default-app
  labels:
    app: go-app
spec:
  type: NodePort
  selector:
    app: go-app
  ports:
    - name: http 
      port: 80
      targetPort: 8080
