name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Build the Go App Image
      # Changed '.' to 'cmd/app/' so it finds the Dockerfile
      # Updated image name to match your Docker Hub
      - name: Build Docker Image
        run: docker build -t jaiminops18/go-app:latest cmd/app/

      # 2. Run Trivy Scan
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          #Must match the tag we just built above
          image-ref: 'jaiminops18/go-app:latest' 
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'          
